import { Router } from 'express';
import { z } from 'zod';
import { query, transaction } from './db.js';
import { ApiError, asyncRoute, ok } from './http.js';
import { requireAuth, signToken, verifyPassword } from './auth.js';
import { assertTransition, recalculateQueue } from './queue.js';
import { emitQueueUpdate } from './socket.js';
import { TokenStatus } from './types.js';

const id = z.string().uuid();
const tokenInput = z.object({ customerName: z.string().trim().min(2).max(100), mobile: z.string().regex(/^\d{10,15}$/), branchId: id, serviceId: id });
const callInput = z.object({ serviceId: id, counterId: id });
const counterInput = z.object({ counterId: id });
const json = <T>(schema: z.ZodType<T>, value: unknown): T => { const parsed = schema.safeParse(value); if (!parsed.success) throw new ApiError(400, 'VALIDATION_ERROR', parsed.error.issues.map(x => x.message).join(', ')); return parsed.data; };
const tokenSelect = `select t.*, s.name as service_name, s.average_duration, c.name as counter_name from public.tokens t join public.services s on s.id=t.service_id left join public.counters c on c.id=t.counter_id`;

async function publish(branchId: string, event: string, token?: unknown) {
  const queue = await query(`${tokenSelect} where t.branch_id=$1 order by case when t.status='waiting' then 0 else 1 end, t.queue_position nulls last, t.created_at`, [branchId]);
  emitQueueUpdate(branchId, event, { token, queue: queue.rows });
  emitQueueUpdate(branchId, 'queue-updated', { queue: queue.rows });
}

export const router = Router();
router.get('/health', (_req, res) => ok(res, { timestamp: new Date().toISOString() }, 'QueueLess API is running'));

router.post('/auth/login', asyncRoute(async (req, res) => {
  const { email, password } = json(z.object({ email: z.string().email(), password: z.string().min(1) }), req.body);
  const result = await query<{ id: string; name: string; role: 'admin' | 'staff'; password_hash: string }>('select id,name,role,password_hash from public.users where email=$1 and role in (\'admin\',\'staff\')', [email.toLowerCase()]);
  const user = result.rows[0];
  if (!user || !(await verifyPassword(password, user.password_hash))) throw new ApiError(401, 'UNAUTHORIZED', 'Invalid email or password');
  const safeUser = { id: user.id, name: user.name, role: user.role };
  ok(res, { token: signToken(safeUser), user: safeUser }, 'Logged in successfully');
}));

router.get('/branches', asyncRoute(async (_req, res) => {
  const result = await query(`select b.*, count(t.id) filter (where t.status='waiting')::int as "waitingCount", coalesce(sum(t.estimated_wait_time) filter (where t.status='waiting'),0)::int as "estimatedWaitTime" from public.branches b left join public.tokens t on t.branch_id=b.id group by b.id order by b.name`);
  ok(res, result.rows);
}));
router.get('/branches/:branchId', asyncRoute(async (req, res) => { const result = await query('select * from public.branches where id=$1', [id.parse(req.params.branchId)]); if (!result.rowCount) throw new ApiError(404, 'BRANCH_NOT_FOUND', 'Branch not found'); ok(res, result.rows[0]); }));
router.get('/branches/:branchId/services', asyncRoute(async (req, res) => { const result = await query(`select s.*, count(t.id) filter (where t.status='waiting')::int as "waitingCount" from public.services s left join public.tokens t on t.service_id=s.id where s.branch_id=$1 group by s.id order by s.name`, [id.parse(req.params.branchId)]); ok(res, result.rows); }));
router.post('/services', requireAuth(['admin']), asyncRoute(async (req, res) => { const input = json(z.object({ branchId: id, name: z.string().min(2).max(100), prefix: z.string().min(1).max(8), averageDuration: z.number().int().min(1).max(240) }), req.body); const created = await query('insert into public.services(branch_id,name,prefix,average_duration) values($1,$2,$3,$4) returning *', [input.branchId,input.name,input.prefix.toUpperCase(),input.averageDuration]); ok(res, created.rows[0], 'Service created', 201); }));
router.put('/services/:serviceId', requireAuth(['admin']), asyncRoute(async (req, res) => { const input = json(z.object({ name:z.string().min(2).max(100).optional(), prefix:z.string().min(1).max(8).optional(), averageDuration:z.number().int().min(1).max(240).optional(), status:z.enum(['active','inactive']).optional() }).refine(x => Object.keys(x).length>0), req.body); const result = await query('update public.services set name=coalesce($2,name),prefix=coalesce($3,prefix),average_duration=coalesce($4,average_duration),status=coalesce($5,status) where id=$1 returning *',[id.parse(req.params.serviceId),input.name,input.prefix?.toUpperCase(),input.averageDuration,input.status]); if(!result.rowCount) throw new ApiError(404,'SERVICE_NOT_FOUND','Service not found'); ok(res,result.rows[0],'Service updated'); }));

router.post('/tokens', asyncRoute(async (req, res) => {
  const input = json(tokenInput, req.body);
  const token = await transaction(async client => {
    const service = await client.query<{ id:string; prefix:string; average_duration:number; status:string; branch_status:string }>(`select s.id,s.prefix,s.average_duration,s.status,b.status as branch_status from public.services s join public.branches b on b.id=s.branch_id where s.id=$1 and s.branch_id=$2 for update`,[input.serviceId,input.branchId]);
    const row=service.rows[0]; if(!row) throw new ApiError(404,'SERVICE_NOT_FOUND','Service does not belong to this branch'); if(row.branch_status!=='open') throw new ApiError(409,'BRANCH_CLOSED','Branch is closed'); if(row.status!=='active') throw new ApiError(409,'SERVICE_INACTIVE','Service is inactive');
    const seq = await client.query<{ current_sequence:number }>('update public.services set current_sequence=current_sequence+1 where id=$1 returning current_sequence',[input.serviceId]);
    const sequence=seq.rows[0].current_sequence; const created=await client.query(`insert into public.tokens(token_number,sequence_number,customer_name,mobile,branch_id,service_id) values($1,$2,$3,$4,$5,$6) returning *`,[`${row.prefix}-${sequence}`,sequence,input.customerName,input.mobile,input.branchId,input.serviceId]);
    await recalculateQueue(client,input.serviceId); return (await client.query(`${tokenSelect} where t.id=$1`,[created.rows[0].id])).rows[0];
  });
  await publish(input.branchId,'token-created',token); ok(res,token,'Token created successfully',201);
}));
router.get('/tokens/:tokenId', asyncRoute(async(req,res)=>{const result=await query(`${tokenSelect} where t.id=$1`,[id.parse(req.params.tokenId)]);if(!result.rowCount)throw new ApiError(404,'TOKEN_NOT_FOUND','Token not found');ok(res,result.rows[0]);}));
router.get('/tokens/:tokenId/status', asyncRoute(async(req,res)=>{const result=await query('select id,token_number,status,queue_position,estimated_wait_time,counter_id,updated_at from public.tokens where id=$1',[id.parse(req.params.tokenId)]);if(!result.rowCount)throw new ApiError(404,'TOKEN_NOT_FOUND','Token not found');ok(res,result.rows[0]);}));

router.get('/queues/:branchId', requireAuth(), asyncRoute(async(req,res)=>{const branchId=id.parse(req.params.branchId);const serviceId=req.query.serviceId ? id.parse(req.query.serviceId):undefined;const status=req.query.status ? z.enum(['waiting','called','serving','skipped','completed','cancelled']).parse(req.query.status):undefined; const result=await query(`${tokenSelect} where t.branch_id=$1 and ($2::uuid is null or t.service_id=$2) and ($3::public.token_status is null or t.status=$3) order by case when t.status='waiting' then 0 else 1 end,t.queue_position nulls last,t.created_at`,[branchId,serviceId??null,status??null]);ok(res,result.rows);}));
router.post('/queues/:branchId/call-next', requireAuth(), asyncRoute(async(req,res)=>{const branchId=id.parse(req.params.branchId);const input=json(callInput,req.body);const token=await transaction(async client=>{const counter=await client.query('select id from public.counters where id=$1 and branch_id=$2 and status=\'active\' for update',[input.counterId,branchId]);if(!counter.rowCount)throw new ApiError(404,'COUNTER_NOT_FOUND','An active counter in this branch is required');const next=await client.query<{id:string}>('select id from public.tokens where branch_id=$1 and service_id=$2 and status=\'waiting\' order by coalesce(restored_at,created_at),created_at limit 1 for update skip locked',[branchId,input.serviceId]);if(!next.rowCount)throw new ApiError(409,'EMPTY_QUEUE','No waiting token is available');const updated=await client.query(`update public.tokens set status='called',counter_id=$2,called_at=now() where id=$1 and status='waiting' returning *`,[next.rows[0].id,input.counterId]);await client.query('update public.counters set status=\'busy\' where id=$1',[input.counterId]);await recalculateQueue(client,input.serviceId);return (await client.query(`${tokenSelect} where t.id=$1`,[updated.rows[0].id])).rows[0];});await publish(branchId,'token-called',token);ok(res,token,'Next token called');}));

const updateToken = (next: TokenStatus, needsCounter=false) => asyncRoute(async(req,res)=>{const tokenId=id.parse(req.params.tokenId);const input=needsCounter?json(counterInput,req.body):undefined;const updated=await transaction(async client=>{const found=await client.query<{id:string;status:TokenStatus;service_id:string;branch_id:string;counter_id:string|null}>('select id,status,service_id,branch_id,counter_id from public.tokens where id=$1 for update',[tokenId]);const current=found.rows[0];if(!current)throw new ApiError(404,'TOKEN_NOT_FOUND','Token not found');assertTransition(current.status,next);if(next==='serving'&&!current.counter_id)throw new ApiError(409,'COUNTER_NOT_FOUND','A counter must be assigned before service can start');const counterId=input?.counterId??current.counter_id;if(next==='called'){const counter=await client.query('select id from public.counters where id=$1 and branch_id=$2 and status=\'active\' for update',[counterId,current.branch_id]);if(!counter.rowCount)throw new ApiError(409,'COUNTER_NOT_FOUND','An active counter in this branch is required');await client.query('update public.counters set status=\'busy\' where id=$1',[counterId]);}const fields:Record<TokenStatus,string>={waiting:`status='waiting', counter_id=null, restored_at=now()`,called:`status='called', counter_id=$2, called_at=now()`,serving:`status='serving', service_started_at=now()`,skipped:`status='skipped', skipped_at=now()`,completed:`status='completed', completed_at=now()`,cancelled:`status='cancelled', cancelled_at=now()`};const result=await client.query(`update public.tokens set ${fields[next]} where id=$1 returning *`,next==='called'?[tokenId,counterId]:[tokenId]);if(['completed','skipped','cancelled'].includes(next)&&current.counter_id)await client.query('update public.counters set status=\'active\' where id=$1',[current.counter_id]);await recalculateQueue(client,current.service_id);return {token:(await client.query(`${tokenSelect} where t.id=$1`,[result.rows[0].id])).rows[0],branchId:current.branch_id};});await publish(updated.branchId,`token-${next==='serving'?'started':next}`,updated.token);ok(res,updated.token,`Token ${next}`);});
router.patch('/tokens/:tokenId/call',requireAuth(),updateToken('called',true));router.patch('/tokens/:tokenId/start',requireAuth(),updateToken('serving'));router.patch('/tokens/:tokenId/complete',requireAuth(),updateToken('completed'));router.patch('/tokens/:tokenId/skip',requireAuth(),updateToken('skipped'));router.patch('/tokens/:tokenId/restore',requireAuth(),updateToken('waiting'));router.patch('/tokens/:tokenId/cancel',asyncRoute(async(req,res,next)=>{try{return await updateToken('cancelled')(req,res,next);}catch(error){next(error);}}));

router.get('/counters',requireAuth(),asyncRoute(async(req,res)=>{const branchId=req.query.branchId?id.parse(req.query.branchId):undefined;const result=await query(`select c.*,u.name as staff_name,t.token_number as current_token from public.counters c left join public.users u on u.id=c.staff_id left join public.tokens t on t.counter_id=c.id and t.status in ('called','serving') where ($1::uuid is null or c.branch_id=$1) order by c.name`,[branchId??null]);ok(res,result.rows);}));
router.get('/dashboard/summary',requireAuth(),asyncRoute(async(req,res)=>{const branchId=req.query.branchId?id.parse(req.query.branchId):undefined;const result=await query(`select count(*)::int total,count(*) filter(where status='waiting')::int waiting,count(*) filter(where status='called')::int called,count(*) filter(where status='serving')::int serving,count(*) filter(where status='completed')::int completed,count(*) filter(where status='skipped')::int skipped,count(*) filter(where status='cancelled')::int cancelled,coalesce(round(avg(extract(epoch from (called_at-created_at))/60) filter(where called_at is not null)),0)::int as "averageWaitTime" from public.tokens where ($1::uuid is null or branch_id=$1) and created_at::date=current_date`,[branchId??null]);ok(res,result.rows[0]);}));
router.get('/dashboard/current-serving',requireAuth(),asyncRoute(async(req,res)=>{const branchId=id.parse(req.query.branchId);const result=await query(`${tokenSelect} where t.branch_id=$1 and t.status in ('called','serving') order by t.called_at`,[branchId]);ok(res,result.rows);}));
router.get('/dashboard/analytics',requireAuth(),asyncRoute(async(req,res)=>{const branchId=req.query.branchId?id.parse(req.query.branchId):undefined;const result=await query(`select s.name as service, count(t.id)::int as total, count(t.id) filter(where t.status='completed')::int as completed, coalesce(round(avg(extract(epoch from (t.completed_at-t.service_started_at))/60) filter(where t.completed_at is not null and t.service_started_at is not null)),0)::int as "averageServiceTime" from public.services s left join public.tokens t on t.service_id=s.id and ($1::uuid is null or t.branch_id=$1) where ($1::uuid is null or s.branch_id=$1) group by s.id,s.name order by total desc,s.name`,[branchId??null]);ok(res,{byService:result.rows});}));
router.get('/public-display/:branchId',asyncRoute(async(req,res)=>{const branchId=id.parse(req.params.branchId);const [now,next]=await Promise.all([query(`${tokenSelect} where t.branch_id=$1 and t.status in ('called','serving') order by t.called_at limit 1`,[branchId]),query('select token_number from public.tokens where branch_id=$1 and status=\'waiting\' order by queue_position limit 3',[branchId])]);ok(res,{nowServing:now.rows[0]?{tokenNumber:now.rows[0].token_number,counter:now.rows[0].counter_name}:null,upNext:next.rows.map(x=>x.token_number)});}));
